/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/huracan-falcontm-ac4bfe9c5e8d42fda5691f78e8931b95
title: Huracan Falcon™️
*/

import * as THREE from 'three'
import React, {Ref, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
    Object_41: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_45: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_49: THREE.Mesh
    Object_51: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_57: THREE.Mesh
    Object_59: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_63: THREE.Mesh
    Object_65: THREE.Mesh
    Object_67: THREE.Mesh
    Object_69: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_83: THREE.Mesh
    Object_85: THREE.Mesh
    Object_87: THREE.Mesh
    Object_89: THREE.Mesh
    Object_90: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_95: THREE.Mesh
    Object_97: THREE.Mesh
    Object_99: THREE.Mesh
    Object_101: THREE.Mesh
    Object_102: THREE.Mesh
    Object_104: THREE.Mesh
    Object_106: THREE.Mesh
    Object_107: THREE.Mesh
    Object_108: THREE.Mesh
    Object_109: THREE.Mesh
    Object_110: THREE.Mesh
    Object_111: THREE.Mesh
    Object_112: THREE.Mesh
    Object_113: THREE.Mesh
    Object_114: THREE.Mesh
    Object_116: THREE.Mesh
  }
  materials: {
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    CRBN_JANTE: THREE.MeshStandardMaterial
    ['pneu.005']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    PZEO: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    BLACK: THREE.MeshStandardMaterial
    ['plaquette_de_frein.002']: THREE.MeshStandardMaterial
    ['visse.002']: THREE.MeshStandardMaterial
    Chrome_Text_Logo: THREE.MeshStandardMaterial
    ['Material.038']: THREE.MeshStandardMaterial
    ['Material.039']: THREE.MeshStandardMaterial
    ['pneu.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    ['Material.063']: THREE.MeshStandardMaterial
    ['Material.062']: THREE.MeshStandardMaterial
    drlwhite: THREE.MeshStandardMaterial
    xenonhead: THREE.MeshStandardMaterial
    ['Material.061']: THREE.MeshStandardMaterial
    ['Material.060']: THREE.MeshStandardMaterial
    ['Material.059']: THREE.MeshStandardMaterial
    ['Material.058']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/huracan.glb') as GLTFResult
  return (
    <group ref={group as Ref<THREE.Group>} {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
          <group name="LamborghiniGT3Huracan_3" position={[-4.01, 0, -0.08]} scale={0.03}>
            <group name="Body_2" rotation={[0, 0, Math.PI / 2]} scale={0.1}>
              <group name="LamborghiniHuracanGT3_CarLights_0" position={[-192.22, -1579.68, 30]} rotation={[Math.PI / 2, 0, 0]} scale={48.67}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.017']} />
              </group>
              <group name="LamborghiniHuracanGT3_CarLights001_1" position={[-297.24, -1575.53, -648.24]} rotation={[Math.PI / 2, 0, 0]} scale={69.7}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.017']} />
              </group>
            </group>
          </group>
          <group name="Plane003_4" position={[0, 0.01, 0]} rotation={[-2.83, 0, Math.PI / 2]} scale={0.16}>
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.013']} />
            <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.CRBN_JANTE} />
            <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['pneu.005']} />
            <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['pneu.005']} />
            <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Material.029']} />
            <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials['Material.028']} />
            <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['Material.027']} />
            <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.PZEO} />
            <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Material.025']} />
            <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.BLACK} />
            <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['plaquette_de_frein.002']} />
            <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials['visse.002']} />
            <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Chrome_Text_Logo} />
          </group>
          <group name="Plane001_5" position={[0, 0.01, -3.03]} rotation={[-2.83, 0, Math.PI / 2]} scale={0.16}>
            <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['Material.013']} />
            <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.CRBN_JANTE} />
            <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['pneu.005']} />
            <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials['pneu.005']} />
            <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['Material.029']} />
            <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials['Material.028']} />
            <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Material.027']} />
            <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.PZEO} />
            <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['Material.025']} />
            <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.BLACK} />
            <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials['plaquette_de_frein.002']} />
            <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials['visse.002']} />
            <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.Chrome_Text_Logo} />
          </group>
          <group name="Circle_6" position={[0, 0.91, 0]}>
            <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials['Material.038']} />
            <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials['Material.039']} />
          </group>
          <group name="Cube_7" scale={[1, 0.1, 1]}>
            <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials['pneu.002']} />
          </group>
          <group name="123001_8" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials['Material.001']} />
            <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials['Material.005']} />
            <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials['Material.007']} />
            <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials['Material.009']} />
          </group>
          <group name="123002_9" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials['Material.003']} />
            <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.material_0} />
          </group>
          <group name="123003_10" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials['Material.005']} />
            <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.material_0} />
          </group>
          <group name="123004_11" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials['Material.005']} />
            <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials['Material.012']} />
          </group>
          <group name="123005_12" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials['Material.012']} />
          </group>
          <group name="123006_13" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials['Material.002']} />
            <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials['Material.012']} />
          </group>
          <group name="123007_14" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials['Material.001']} />
            <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials['Material.010']} />
          </group>
          <group name="123008_15" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials['Material.005']} />
          </group>
          <group name="123009_16" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials['Material.001']} />
          </group>
          <group name="123010_17" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials['Material.005']} />
          </group>
          <group name="123011_18" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials['Material.002']} />
          </group>
          <group name="123012_19" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials['Material.005']} />
          </group>
          <group name="123013_20" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials['Material.001']} />
            <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials['Material.005']} />
          </group>
          <group name="123014_21" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials['Material.005']} />
          </group>
          <group name="123016_22" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials['Material.003']} />
          </group>
          <group name="123017_23" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials['Material.002']} />
            <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials['Material.008']} />
          </group>
          <group name="123018_24" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials['Material.002']} />
          </group>
          <group name="123019_25" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials['Material.012']} />
          </group>
          <group name="123020_26" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials['Material.002']} />
            <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials['Material.008']} />
          </group>
          <group name="123022_27" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials['Material.002']} />
          </group>
          <group name="123015_28" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials['Material.005']} />
            <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials['Material.012']} />
          </group>
          <group name="123021_29" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials['Material.004']} />
          </group>
          <group name="123023_30" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials['Material.006']} />
          </group>
          <group name="123024_31" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials['Material.005']} />
            <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials['Material.012']} />
          </group>
          <group name="Plane_32" position={[0, 0.09, 1.2]} scale={[0.56, 1, 1]}>
            <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials['Material.011']} />
          </group>
          <group name="SDC_33" position={[0, -0.48, -0.57]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.63}>
            <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.black} />
            <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials['Material.063']} />
            <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials['Material.062']} />
            <mesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.drlwhite} />
            <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.xenonhead} />
            <mesh name="Object_111" geometry={nodes.Object_111.geometry} material={materials['Material.061']} />
            <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials['Material.060']} />
            <mesh name="Object_113" geometry={nodes.Object_113.geometry} material={materials['Material.059']} />
            <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials['Material.058']} />
          </group>
          <group name="123025_48" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials['Material.037']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/huracan.glb')
