/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: akshatmittal (https://sketchfab.com/akshatmittal)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/2021-macbook-pro-14-m1-pro-m1-max-f6b0b940fb6a4286b18a674ef32af2d3
title: 2021 Macbook Pro 14" (M1 Pro / M1 Max)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    WeTEPJkcTkMBwBo: THREE.Mesh
    yxTDdMZViYkuOKm: THREE.Mesh
    pPCeNYAcgHQGnfB: THREE.Mesh
    CpRxqsFibJhVZKA: THREE.Mesh
    abgVijaHVNRUvcc: THREE.Mesh
    CEvArJuvvmtQsgk: THREE.Mesh
    aUVveCqqwsqchVB: THREE.Mesh
    fiqlelggeOoTUAw: THREE.Mesh
    zlRXoydEgBQgFUa: THREE.Mesh
    YvEVHGlTGUxXlGj: THREE.Mesh
    FnbkdmFKVeCCxTX: THREE.Mesh
    ehiyYGFzDbgxhiD: THREE.Mesh
    NhThIZELXlNUoIr: THREE.Mesh
    RYgQzNzcnFbacQH: THREE.Mesh
    JtnJKXAEPaOoepM: THREE.Mesh
    UxiDBlCRfXiMBzT: THREE.Mesh
    NgmQYtxXWDmCavo: THREE.Mesh
    PSIiVLWbMOjTmDb: THREE.Mesh
    RkSurqpnfNMQZfv: THREE.Mesh
    YJMoQnvBNpTrgeH: THREE.Mesh
    KCEhahuknsxQOxv: THREE.Mesh
    tEHnKyDsqJuxIpz: THREE.Mesh
    TCGsaoyNbPKzeSS: THREE.Mesh
    DAuseNOrQKyrxKl: THREE.Mesh
    SjXIFRJFXEqYDUr: THREE.Mesh
    eAcvqfZlEdoxHsj: THREE.Mesh
    gkxaPoMYYRpyVMR: THREE.Mesh
    xlRLalLTesirCGW: THREE.Mesh
    ZlizOzukFeXwbga: THREE.Mesh
    wXiLpiodZWNDroe: THREE.Mesh
    PTxrSKzcEmHVtif: THREE.Mesh
    RjGOdbHqvxkiDns: THREE.Mesh
    WPFmzKypKbUYgQT: THREE.Mesh
    QHqPxKdexBoFnAK: THREE.Mesh
    NWErafhynAfYQEz: THREE.Mesh
    tEwRkclpxjXZzil: THREE.Mesh
    QYMcPaZnXQfyXcJ: THREE.Mesh
    piXptsgcOfaGWrM: THREE.Mesh
    SjSNuZdtWKZRuoq: THREE.Mesh
    QFFLzaWPRnuQYJR: THREE.Mesh
    xjTvBwZFGvSMOud: THREE.Mesh
    VqfccLWHjnpnmIO: THREE.Mesh
    mUrIWHenIQKVHcb: THREE.Mesh
    NdRhLFCrSxRNTxn: THREE.Mesh
    vivXPkdlqllUnrl: THREE.Mesh
    rIsAbujsARaHSub: THREE.Mesh
    QMBrsnrwfcVKELm: THREE.Mesh
    NqLxSKdAypgOdPC: THREE.Mesh
    guoofBSjCEiTIJr: THREE.Mesh
    jvyJQHpRnZNPEYh: THREE.Mesh
  }
  materials: {
    lbGSuJJwEsUTzIm: THREE.MeshStandardMaterial
    BczvixNfkWQzRzZ: THREE.MeshStandardMaterial
    jRMWtdSAaujlvUA: THREE.MeshStandardMaterial
    CGiumILqqSMVyeb: THREE.MeshStandardMaterial
    UpOvKwLUUXPmnPU: THREE.MeshStandardMaterial
    yVmFXNTCIwNkqVT: THREE.MeshStandardMaterial
    SELuppcPLrlTpBi: THREE.MeshStandardMaterial
    zqeFZcIteZtOShc: THREE.MeshStandardMaterial
    initialShadingGroup: THREE.MeshStandardMaterial
    ZpTrUizuxJQUyzW: THREE.MeshStandardMaterial
    LJSCtLIrHNHZnIH: THREE.MeshStandardMaterial
    mpJhsaJJZPPWMEX: THREE.MeshStandardMaterial
    VfcxYmbOfnqunYx: THREE.MeshStandardMaterial
    zWLcvvnJhbcTEtJ: THREE.MeshStandardMaterial
    SKOFticEGTqECbB: THREE.MeshStandardMaterial
    PCfVLhSpFVCvRmc: THREE.MeshStandardMaterial
    HpEeGHRuOqfcIZU: THREE.MeshStandardMaterial
    IlNnjEDxsExlBOr: THREE.MeshStandardMaterial
    iPZiEncThgnBMJv: THREE.MeshStandardMaterial
    hPcehRUjcLAosED: THREE.MeshStandardMaterial
    kOcboIDeohDRqCf: THREE.MeshStandardMaterial
    HPAOpCInJKBtaOC: THREE.MeshStandardMaterial
    zaEqorbaeeADKgU: THREE.MeshStandardMaterial
    pZbDFXVUkfRwjmQ: THREE.MeshStandardMaterial
    UPMcPXFSRXevSGt: THREE.MeshStandardMaterial
    NQXltfOcKPZPQdI: THREE.MeshStandardMaterial
    WLATjirhQCUYAAG: THREE.MeshStandardMaterial
    BMKLbAPYqPmfArt: THREE.MeshStandardMaterial
    XNDkEZQapqqDHpk: THREE.MeshStandardMaterial
    jAWKNAaRBMlZYro: THREE.MeshStandardMaterial
    VqwNZwmDotIMflD: THREE.MeshStandardMaterial
    JjuwNKnMBUdtRLb: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/3ds/macbook.glb') as GLTFResult
  return (
      // @ts-ignore
      <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.WeTEPJkcTkMBwBo.geometry} material={materials.lbGSuJJwEsUTzIm} />
          <mesh geometry={nodes.yxTDdMZViYkuOKm.geometry} material={materials.BczvixNfkWQzRzZ} />
          <mesh geometry={nodes.pPCeNYAcgHQGnfB.geometry} material={materials.jRMWtdSAaujlvUA} />
          <mesh geometry={nodes.CpRxqsFibJhVZKA.geometry} material={materials.CGiumILqqSMVyeb} />
          <mesh geometry={nodes.abgVijaHVNRUvcc.geometry} material={materials.UpOvKwLUUXPmnPU} />
          <mesh geometry={nodes.CEvArJuvvmtQsgk.geometry} material={materials.yVmFXNTCIwNkqVT} />
          <mesh geometry={nodes.aUVveCqqwsqchVB.geometry} material={materials.yVmFXNTCIwNkqVT} />
          <mesh geometry={nodes.fiqlelggeOoTUAw.geometry} material={materials.SELuppcPLrlTpBi} />
          <mesh geometry={nodes.zlRXoydEgBQgFUa.geometry} material={materials.zqeFZcIteZtOShc} />
          <mesh geometry={nodes.YvEVHGlTGUxXlGj.geometry} material={materials.initialShadingGroup} />
          <mesh geometry={nodes.FnbkdmFKVeCCxTX.geometry} material={materials.ZpTrUizuxJQUyzW} />
          <mesh geometry={nodes.ehiyYGFzDbgxhiD.geometry} material={materials.LJSCtLIrHNHZnIH} />
          <mesh geometry={nodes.NhThIZELXlNUoIr.geometry} material={materials.mpJhsaJJZPPWMEX} />
          <mesh geometry={nodes.RYgQzNzcnFbacQH.geometry} material={materials.VfcxYmbOfnqunYx} />
          <mesh geometry={nodes.JtnJKXAEPaOoepM.geometry} material={materials.lbGSuJJwEsUTzIm} />
          <mesh geometry={nodes.UxiDBlCRfXiMBzT.geometry} material={materials.zWLcvvnJhbcTEtJ} />
          <mesh geometry={nodes.NgmQYtxXWDmCavo.geometry} material={materials.SKOFticEGTqECbB} />
          <mesh geometry={nodes.PSIiVLWbMOjTmDb.geometry} material={materials.SKOFticEGTqECbB} />
          <mesh geometry={nodes.RkSurqpnfNMQZfv.geometry} material={materials.zWLcvvnJhbcTEtJ} />
          <mesh geometry={nodes.YJMoQnvBNpTrgeH.geometry} material={materials.PCfVLhSpFVCvRmc} />
          <mesh geometry={nodes.KCEhahuknsxQOxv.geometry} material={materials.HpEeGHRuOqfcIZU} />
          <mesh geometry={nodes.tEHnKyDsqJuxIpz.geometry} material={materials.yVmFXNTCIwNkqVT} />
          <mesh geometry={nodes.TCGsaoyNbPKzeSS.geometry} material={materials.yVmFXNTCIwNkqVT} />
          <mesh geometry={nodes.DAuseNOrQKyrxKl.geometry} material={materials.yVmFXNTCIwNkqVT} />
          <mesh geometry={nodes.SjXIFRJFXEqYDUr.geometry} material={materials.PCfVLhSpFVCvRmc} />
          <mesh geometry={nodes.eAcvqfZlEdoxHsj.geometry} material={materials.IlNnjEDxsExlBOr} />
          <mesh geometry={nodes.gkxaPoMYYRpyVMR.geometry} material={materials.iPZiEncThgnBMJv} />
          <mesh geometry={nodes.xlRLalLTesirCGW.geometry} material={materials.hPcehRUjcLAosED} />
          <mesh geometry={nodes.ZlizOzukFeXwbga.geometry} material={materials.kOcboIDeohDRqCf} />
          <mesh geometry={nodes.wXiLpiodZWNDroe.geometry} material={materials.HPAOpCInJKBtaOC} />
          <mesh geometry={nodes.PTxrSKzcEmHVtif.geometry} material={materials.VfcxYmbOfnqunYx} />
          <mesh geometry={nodes.RjGOdbHqvxkiDns.geometry} material={materials.lbGSuJJwEsUTzIm} />
          <mesh geometry={nodes.WPFmzKypKbUYgQT.geometry} material={materials.lbGSuJJwEsUTzIm} />
          <mesh geometry={nodes.QHqPxKdexBoFnAK.geometry} material={materials.zaEqorbaeeADKgU} />
          <mesh geometry={nodes.NWErafhynAfYQEz.geometry} material={materials.pZbDFXVUkfRwjmQ} />
          <mesh geometry={nodes.tEwRkclpxjXZzil.geometry} material={materials.UPMcPXFSRXevSGt} />
          <mesh geometry={nodes.QYMcPaZnXQfyXcJ.geometry} material={materials.NQXltfOcKPZPQdI} />
          <mesh geometry={nodes.piXptsgcOfaGWrM.geometry} material={materials.WLATjirhQCUYAAG} />
          <mesh geometry={nodes.SjSNuZdtWKZRuoq.geometry} material={materials.mpJhsaJJZPPWMEX} />
          <mesh geometry={nodes.QFFLzaWPRnuQYJR.geometry} material={materials.hPcehRUjcLAosED} />
          <mesh geometry={nodes.xjTvBwZFGvSMOud.geometry} material={materials.hPcehRUjcLAosED} />
          <mesh geometry={nodes.VqfccLWHjnpnmIO.geometry} material={materials.BMKLbAPYqPmfArt} />
          <mesh geometry={nodes.mUrIWHenIQKVHcb.geometry} material={materials.BMKLbAPYqPmfArt} />
          <mesh geometry={nodes.NdRhLFCrSxRNTxn.geometry} material={materials.BMKLbAPYqPmfArt} />
          <mesh geometry={nodes.vivXPkdlqllUnrl.geometry} material={materials.XNDkEZQapqqDHpk} />
          <mesh geometry={nodes.rIsAbujsARaHSub.geometry} material={materials.jAWKNAaRBMlZYro} />
          <mesh geometry={nodes.QMBrsnrwfcVKELm.geometry} material={materials.VqwNZwmDotIMflD} />
          <mesh geometry={nodes.NqLxSKdAypgOdPC.geometry} material={materials.initialShadingGroup} />
          <mesh geometry={nodes.guoofBSjCEiTIJr.geometry} material={materials.JjuwNKnMBUdtRLb} />
          <mesh geometry={nodes.jvyJQHpRnZNPEYh.geometry} material={materials.LJSCtLIrHNHZnIH} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3ds/macbook.glb')
