-- Admin tracking seed data. LOCAL DEVELOPMENT ONLY (same stance as seeds/demo.sql):
--   wrangler d1 execute micvolo --local --file=./seeds/admin-tracking.sql

INSERT INTO tracking_projects (slug, title, description, rate, sort_order) VALUES
  ('davide-derocchi', 'Davide Derocchi', 'Portfolio — pagine ciclo, gallerie fluide e visualizzatore a schermo intero', 40, 0),
  ('ea-kahane', 'E.A. Kahane', 'Portfolio — archivio opere con tavole a tutta pagina e timeline mostre', 40, 1),
  ('miriam-mora', 'Miriam Mora', 'Portfolio — pagine progetto con ritratti in coppia e note affiancate', 40, 2),
  ('abitare-in-legno', 'Abitare in Legno', 'Sito immobiliare X-Lam — storytelling delle residenze, reveal a scorrimento e budget di rendering stretto', 40, 3),
  ('studio-psicologia-doria', 'Studio Psicologia Doria', 'Sito dello studio — pagine percorsi e passaggio al calendario', 40, 4),
  ('fame-la-frittura-di-napoli', 'Fame — La Frittura di Napoli', 'Sito del locale — template menù e presa fotografica', 40, 5),
  ('momento-golf', 'Momento Golf', 'Negozio online — configuratore mazze e catalogo da tastiera', 40, 6),
  ('pasolini', 'Pasolini', 'Sito istituzionale — mostre, ricerca archivio e pagine evento', 40, 7),
  ('apr-instruments', 'APR Instruments', 'Shop Shopify su misura — visualizzatore Microcamera WebGL e interazioni da tastiera', 30, 8),
  ('music-mascots-archive', 'Music Mascots Archive', 'Archivio pubblico — schede mascotte con filtri, ricerca e anteprime WebGL', 30, 9),
  ('gastronomia-lanzani', 'Gastronomia Lanzani', 'Sito della gastronomia — registro prodotti e aggiornamenti di stagione', 30, 10),
  ('lorem', 'Lorem', 'Catalogo componenti — esempi dal vivo e registro codice', 30, 11),
  ('laura-baresi', 'Laura Baresi', 'Negozio online — varianti, lookbook e import catalogo', 28, 12),
  ('origami-project', 'Origami Project', 'Sito del progetto — calendario laboratori e archivio', 28, 13),
  ('omb-saleri', 'OMB Saleri', 'Sito aziendale — catalogo prodotti, schede tecniche e tre lingue', 25, 14),
  ('flavio-nani', 'Flavio Nani', 'Sito personale — registro ruoli e news', 25, 15),
  ('the-big-archive', 'The Big Archive', 'Archivio di siti — pipeline di cattura e schede con registro metadati', 25, 16),
  ('massimo-uberti', 'Massimo Uberti', 'Sito d''artista — archivio opere, mostre e bibliografia', 22, 17),
  ('francesco-bellisario', 'Francesco Bellisario', 'Sito personale — archivio fotografico con gallerie a tutta pagina', 22, 18),
  ('bloem', 'Bloem', 'Testata editoriale longform — template numero e sistema tipografico da lettura', 20, 19);

INSERT INTO estimate_docs (id, slug, date, hours, amount, note, pdf_url) VALUES
  ('est_davide-derocchi_01', 'davide-derocchi', '2025-11-17', 60, 2400, 'stimo 60 ore a 2400 euro per il portfolio', '/preventivi/davide-derocchi/est_davide-derocchi_01.pdf'),
  ('est_davide-derocchi_02', 'davide-derocchi', '2026-06-08', 20, 800, 'il cliente chiede l''archivio stampa — stimo 20 ore a 800 euro', '/preventivi/davide-derocchi/est_davide-derocchi_02.pdf'),
  ('est_ea-kahane_01', 'ea-kahane', '2025-11-10', 70, 2800, 'stimo 70 ore a 2800 euro per l''archivio opere', '/preventivi/ea-kahane/est_ea-kahane_01.pdf'),
  ('est_ea-kahane_02', 'ea-kahane', '2026-05-25', 20, 800, 'il cliente chiede ricerca e filtri sull''archivio — stimo 20 ore a 800 euro', '/preventivi/ea-kahane/est_ea-kahane_02.pdf'),
  ('est_miriam-mora_01', 'miriam-mora', '2025-11-24', 80, 3200, 'stimo 80 ore a 3200 euro per il portfolio', '/preventivi/miriam-mora/est_miriam-mora_01.pdf'),
  ('est_abitare-in-legno_01', 'abitare-in-legno', '2025-08-04', 80, 3200, 'stimo 80 ore a 3200 euro per il nuovo sito', '/preventivi/abitare-in-legno/est_abitare-in-legno_01.pdf'),
  ('est_abitare-in-legno_02', 'abitare-in-legno', '2026-04-20', 10, 400, 'il cliente aggiunge la fase di nuovi appartamenti — stimo 10 ore a 400 euro', '/preventivi/abitare-in-legno/est_abitare-in-legno_02.pdf'),
  ('est_abitare-in-legno_03', 'abitare-in-legno', '2026-07-10', 15, 600, 'supporto alle pubblicazioni per l''estate — stimo 15 ore a 600 euro', '/preventivi/abitare-in-legno/est_abitare-in-legno_03.pdf'),
  ('est_studio-psicologia-doria_01', 'studio-psicologia-doria', '2025-09-08', 30, 1200, 'stimo 30 ore a 1200 euro per lo studio', '/preventivi/studio-psicologia-doria/est_studio-psicologia-doria_01.pdf'),
  ('est_fame-la-frittura-di-napoli_01', 'fame-la-frittura-di-napoli', '2025-03-24', 50, 2000, 'stimo 50 ore a 2000 euro per il sito del locale', '/preventivi/fame-la-frittura-di-napoli/est_fame-la-frittura-di-napoli_01.pdf'),
  ('est_momento-golf_01', 'momento-golf', '2024-12-16', 90, 3600, 'stimo 90 ore a 3600 euro per il negozio online', '/preventivi/momento-golf/est_momento-golf_01.pdf'),
  ('est_pasolini_01', 'pasolini', '2025-01-27', 65, 2600, 'stimo 65 ore a 2600 euro per il sito istituzionale', '/preventivi/pasolini/est_pasolini_01.pdf'),
  ('est_apr-instruments_01', 'apr-instruments', '2024-06-24', 60, 1800, 'stimo 60 ore a 1800 euro per lo shop su misura', '/preventivi/apr-instruments/est_apr-instruments_01.pdf'),
  ('est_apr-instruments_02', 'apr-instruments', '2024-12-02', 15, 450, 'servono le revisioni del catalogo prima del lancio — stimo 15 ore a 450 euro', '/preventivi/apr-instruments/est_apr-instruments_02.pdf'),
  ('est_music-mascots-archive_01', 'music-mascots-archive', '2024-02-26', 75, 2250, 'stimo 75 ore a 2250 euro per l''archivio pubblico', '/preventivi/music-mascots-archive/est_music-mascots-archive_01.pdf'),
  ('est_gastronomia-lanzani_01', 'gastronomia-lanzani', '2024-01-22', 50, 1500, 'stimo 50 ore a 1500 euro per il sito della gastronomia', '/preventivi/gastronomia-lanzani/est_gastronomia-lanzani_01.pdf'),
  ('est_lorem_01', 'lorem', '2024-01-29', 45, 1350, 'stimo 45 ore a 1350 euro per il catalogo componenti', '/preventivi/lorem/est_lorem_01.pdf'),
  ('est_laura-baresi_01', 'laura-baresi', '2023-11-20', 75, 2100, 'stimo 75 ore a 2100 euro per il negozio online', '/preventivi/laura-baresi/est_laura-baresi_01.pdf'),
  ('est_origami-project_01', 'origami-project', '2023-08-14', 50, 1400, 'stimo 50 ore a 1400 euro per il sito del progetto', '/preventivi/origami-project/est_origami-project_01.pdf'),
  ('est_omb-saleri_01', 'omb-saleri', '2023-04-24', 75, 1875, 'stimo 75 ore a 1875 euro per il sito aziendale', '/preventivi/omb-saleri/est_omb-saleri_01.pdf'),
  ('est_flavio-nani_01', 'flavio-nani', '2022-12-19', 35, 875, 'stimo 35 ore a 875 euro per il sito personale', '/preventivi/flavio-nani/est_flavio-nani_01.pdf'),
  ('est_the-big-archive_01', 'the-big-archive', '2022-08-01', 75, 1875, 'stimo 75 ore a 1875 euro per l''archivio', '/preventivi/the-big-archive/est_the-big-archive_01.pdf'),
  ('est_the-big-archive_02', 'the-big-archive', '2023-02-06', 25, 625, 'l''archivio cresce oltre il previsto — stimo 25 ore a 625 euro', '/preventivi/the-big-archive/est_the-big-archive_02.pdf'),
  ('est_massimo-uberti_01', 'massimo-uberti', '2022-10-24', 40, 880, 'stimo 40 ore a 880 euro per l''archivio opere', '/preventivi/massimo-uberti/est_massimo-uberti_01.pdf'),
  ('est_francesco-bellisario_01', 'francesco-bellisario', '2022-10-03', 30, 660, 'stimo 30 ore a 660 euro per il sito personale', '/preventivi/francesco-bellisario/est_francesco-bellisario_01.pdf'),
  ('est_bloem_01', 'bloem', '2021-09-06', 40, 800, 'stimo 40 ore a 800 euro per la testata', '/preventivi/bloem/est_bloem_01.pdf');

INSERT INTO time_entries (id, slug, date, hours, note) VALUES
  ('log_davide-derocchi_01', 'davide-derocchi', '2025-12-02', 7, 'prima chiamata e audit contenuti — struttura dei cicli e piano archivio immagini'),
  ('log_davide-derocchi_02', 'davide-derocchi', '2025-12-19', 8, 'traduzione della griglia dello studio nei template portfolio'),
  ('log_davide-derocchi_03', 'davide-derocchi', '2026-01-13', 8, 'pagine ciclo con gallerie fluide e visualizzatore a schermo intero'),
  ('log_davide-derocchi_04', 'davide-derocchi', '2026-02-03', 8, 'integrazione CMS per cicli, didascalie e press'),
  ('log_davide-derocchi_05', 'davide-derocchi', '2026-02-24', 7, 'revisioni con lo studio di graphic design sulla sequenza di copertina e l''abbinamento dei font'),
  ('log_davide-derocchi_06', 'davide-derocchi', '2026-03-10', 8, 'passata responsive — ritratti in coppia e quad 2×2 sotto 721px'),
  ('log_davide-derocchi_07', 'davide-derocchi', '2026-03-26', 6, 'messa online e QA sul dominio di produzione'),
  ('log_davide-derocchi_08', 'davide-derocchi', '2026-05-28', 5, 'nuovo ciclo pubblicato dal CMS, template galleria esteso'),
  ('log_davide-derocchi_09', 'davide-derocchi', '2026-08-25', 5, 'passata performance sulle gallerie lazy e sul form contatti'),
  ('log_ea-kahane_01', 'ea-kahane', '2025-11-25', 7, 'prima chiamata — archivio opere e timeline biografica'),
  ('log_ea-kahane_02', 'ea-kahane', '2025-12-16', 8, 'traduzione della griglia editoriale dello studio nei template opere'),
  ('log_ea-kahane_03', 'ea-kahane', '2026-01-08', 8, 'pagine opera con tavole a tutta pagina e registro didascalie'),
  ('log_ea-kahane_04', 'ea-kahane', '2026-01-27', 8, 'passata tipografica — asse di larghezza variabile e tracking dallo spec di brand'),
  ('log_ea-kahane_05', 'ea-kahane', '2026-02-12', 7, 'integrazione CMS per opere, testi e mostre'),
  ('log_ea-kahane_06', 'ea-kahane', '2026-02-26', 8, 'revisioni con lo studio di graphic design sulla sequenza delle tavole'),
  ('log_ea-kahane_07', 'ea-kahane', '2026-03-12', 8, 'passata responsive e pulizia accessibilità, focus sull''accento'),
  ('log_ea-kahane_08', 'ea-kahane', '2026-03-26', 6, 'messa online e QA sul dominio di produzione'),
  ('log_ea-kahane_09', 'ea-kahane', '2026-06-16', 5, 'filtri e ricerca sull''indice opere'),
  ('log_ea-kahane_10', 'ea-kahane', '2026-09-01', 5, 'passata performance — budget immagini e LCP sulle pagine opere'),
  ('log_miriam-mora_01', 'miriam-mora', '2025-12-09', 7, 'prima chiamata e audit materiali — progetti e archivio stampa'),
  ('log_miriam-mora_02', 'miriam-mora', '2026-01-06', 8, 'traduzione dei layout dello studio nei template progetto'),
  ('log_miriam-mora_03', 'miriam-mora', '2026-01-27', 8, 'pagine progetto con ritratti in coppia e note affiancate'),
  ('log_miriam-mora_04', 'miriam-mora', '2026-02-10', 8, 'integrazione CMS per progetti, press e biografia'),
  ('log_miriam-mora_05', 'miriam-mora', '2026-02-24', 7, 'revisioni con lo studio di graphic design sull''ordine dell''indice e sui crop'),
  ('log_miriam-mora_06', 'miriam-mora', '2026-03-10', 8, 'passata responsive — paesaggi in coppia a mezza larghezza, quad in 2×2'),
  ('log_miriam-mora_07', 'miriam-mora', '2026-03-26', 6, 'messa online e QA sul dominio di produzione'),
  ('log_miriam-mora_08', 'miriam-mora', '2026-05-12', 5, 'nuovo progetto pubblicato dal CMS'),
  ('log_miriam-mora_09', 'miriam-mora', '2026-07-21', 5, 'shader WebGL ambientale sulla palette del sito'),
  ('log_miriam-mora_10', 'miriam-mora', '2026-09-08', 4, 'passata performance — budget immagini e subset dei font'),
  ('log_abitare-in-legno_01', 'abitare-in-legno', '2025-08-14', 7, 'prima chiamata con lo studio e il cliente, mappa del sito e modello dati appartamenti'),
  ('log_abitare-in-legno_02', 'abitare-in-legno', '2025-08-29', 8, 'traduzione del progetto grafico del brochure nella griglia CSS, ritmo 8px sull''unità stampa 4mm'),
  ('log_abitare-in-legno_03', 'abitare-in-legno', '2025-09-12', 8, 'hero con drone su layer composited, parallasse 0,14× allo scroll senza reflow'),
  ('log_abitare-in-legno_04', 'abitare-in-legno', '2025-09-30', 7, 'revisioni con lo studio di graphic design sul titolo e sul tracking'),
  ('log_abitare-in-legno_05', 'abitare-in-legno', '2025-10-17', 8, 'template appartamenti con galleria e tabelle tecniche'),
  ('log_abitare-in-legno_06', 'abitare-in-legno', '2025-11-07', 8, 'integrazione CMS per appartamenti, planimetrie e pagine residenza'),
  ('log_abitare-in-legno_07', 'abitare-in-legno', '2025-11-28', 7, 'materiale dello studio preso in consegna — wordmark a layer e planimetrie'),
  ('log_abitare-in-legno_08', 'abitare-in-legno', '2025-12-19', 8, 'passata responsive e performance dei reveal, un solo IntersectionObserver'),
  ('log_abitare-in-legno_09', 'abitare-in-legno', '2026-01-15', 8, 'messa online, DNS e test sul dominio di produzione'),
  ('log_abitare-in-legno_10', 'abitare-in-legno', '2026-03-12', 6, 'correzioni post-lancio sul form contatti e nuovi campi CMS per la fase nuova'),
  ('log_abitare-in-legno_11', 'abitare-in-legno', '2026-06-04', 5, 'workflow di pubblicazione per il team, ritocchi al CMS'),
  ('log_abitare-in-legno_12', 'abitare-in-legno', '2026-09-08', 5, 'passata performance sulle gallerie e budget immagini'),
  ('log_studio-psicologia-doria_01', 'studio-psicologia-doria', '2025-09-23', 4, 'prima chiamata e struttura — approccio, percorsi e contatti'),
  ('log_studio-psicologia-doria_02', 'studio-psicologia-doria', '2025-10-14', 5, 'traduzione dell''identità calma dello studio nei template di pagina'),
  ('log_studio-psicologia-doria_03', 'studio-psicologia-doria', '2025-11-04', 5, 'pagine percorsi con passaggio al calendario dello studio'),
  ('log_studio-psicologia-doria_04', 'studio-psicologia-doria', '2025-11-25', 5, 'integrazione CMS per percorsi, articoli e note disponibilità'),
  ('log_studio-psicologia-doria_05', 'studio-psicologia-doria', '2025-12-31', 5, 'ritocchi alla scala tipografica con lo studio, poi messa online'),
  ('log_fame-la-frittura-di-napoli_01', 'fame-la-frittura-di-napoli', '2025-04-08', 5, 'prima chiamata e piano contenuti — menù, storia e pagine locali'),
  ('log_fame-la-frittura-di-napoli_02', 'fame-la-frittura-di-napoli', '2025-04-29', 7, 'traduzione della palette calda del brand nei template di pagina'),
  ('log_fame-la-frittura-di-napoli_03', 'fame-la-frittura-di-napoli', '2025-05-20', 8, 'template menù con lista fritta e note allergeni'),
  ('log_fame-la-frittura-di-napoli_04', 'fame-la-frittura-di-napoli', '2025-06-10', 7, 'integrazione CMS per menù e orari'),
  ('log_fame-la-frittura-di-napoli_05', 'fame-la-frittura-di-napoli', '2025-06-27', 6, 'presa fotografica — piatti e sala nel budget immagini'),
  ('log_fame-la-frittura-di-napoli_06', 'fame-la-frittura-di-napoli', '2025-07-15', 6, 'revisioni con lo studio di graphic design sull''hero e sul tipo del menù'),
  ('log_fame-la-frittura-di-napoli_07', 'fame-la-frittura-di-napoli', '2025-08-01', 5, 'messa online, mappa e primo SEO locale'),
  ('log_momento-golf_01', 'momento-golf', '2025-01-14', 7, 'prima chiamata e schema catalogo — prodotti, opzioni fitting e giacenze'),
  ('log_momento-golf_02', 'momento-golf', '2025-02-04', 8, 'traduzione del brand deck dello studio nei template shop'),
  ('log_momento-golf_03', 'momento-golf', '2025-02-25', 8, 'configuratore prodotto per opzioni e schede tecniche mazze'),
  ('log_momento-golf_04', 'momento-golf', '2025-03-18', 8, 'carrello e ordini collegati al backend dello shop'),
  ('log_momento-golf_05', 'momento-golf', '2025-04-08', 7, 'integrazione CMS per collezioni, journal e pagine fitting'),
  ('log_momento-golf_06', 'momento-golf', '2025-04-29', 8, 'import catalogo e passata fotografica prodotti'),
  ('log_momento-golf_07', 'momento-golf', '2025-05-20', 7, 'revisioni con lo studio di graphic design sull''hero e l''abbinamento dei font'),
  ('log_momento-golf_08', 'momento-golf', '2025-06-10', 8, 'passata responsive e navigazione da tastiera sul catalogo'),
  ('log_momento-golf_09', 'momento-golf', '2025-07-08', 8, 'passata performance — budget immagini, LCP sotto 2s sulle collezioni'),
  ('log_momento-golf_10', 'momento-golf', '2025-07-29', 6, 'messa online e QA del flusso ordini'),
  ('log_pasolini_01', 'pasolini', '2025-02-11', 6, 'prima chiamata e struttura contenuti — mostre, archivio e pagine visita'),
  ('log_pasolini_02', 'pasolini', '2025-03-04', 8, 'traduzione della grafica mostra nei template di pagina'),
  ('log_pasolini_03', 'pasolini', '2025-03-25', 8, 'pagine mostra con tavole sala e registro opere'),
  ('log_pasolini_04', 'pasolini', '2025-04-15', 7, 'integrazione CMS per mostre, eventi e news'),
  ('log_pasolini_05', 'pasolini', '2025-05-06', 6, 'ricerca sull''archivio opere'),
  ('log_pasolini_06', 'pasolini', '2025-05-27', 6, 'revisioni con lo studio di graphic design sui manifesti e sul titolo'),
  ('log_pasolini_07', 'pasolini', '2025-06-24', 7, 'studio di luce WebGL sull''hero sulla palette dei manifesti'),
  ('log_pasolini_08', 'pasolini', '2025-07-29', 6, 'passata responsive e messa online'),
  ('log_apr-instruments_01', 'apr-instruments', '2024-07-09', 6, 'prima chiamata e architettura del tema, schema catalogo con lo studio'),
  ('log_apr-instruments_02', 'apr-instruments', '2024-07-25', 8, 'traduzione della griglia editoriale a 12 colonne nel layer del tema'),
  ('log_apr-instruments_03', 'apr-instruments', '2024-08-14', 8, 'visualizzatore Microcamera con texture blending WebGL sui quattro scatti'),
  ('log_apr-instruments_04', 'apr-instruments', '2024-09-03', 6, 'mega menu e tabelle prodotto bloccati sui gutter stampa da 24px'),
  ('log_apr-instruments_05', 'apr-instruments', '2024-09-26', 7, 'revisioni con lo studio di graphic design sull''accento e sui pesi del wordmark'),
  ('log_apr-instruments_06', 'apr-instruments', '2024-10-15', 8, 'template prodotto e selettori di variante'),
  ('log_apr-instruments_07', 'apr-instruments', '2024-11-05', 6, 'import catalogo e taglio immagini nel budget da 2,1MB'),
  ('log_apr-instruments_08', 'apr-instruments', '2024-11-27', 5, 'giri di revisione sullo staging, note di art direction risolte pagina per pagina'),
  ('log_apr-instruments_09', 'apr-instruments', '2024-12-17', 7, 'passata responsive e modello di interazione da tastiera'),
  ('log_apr-instruments_10', 'apr-instruments', '2025-01-16', 6, 'messa online e QA del catalogo sullo shop di produzione'),
  ('log_music-mascots-archive_01', 'music-mascots-archive', '2024-03-12', 6, 'prima chiamata e tassonomia — etichette, epoche e indice mascotte'),
  ('log_music-mascots-archive_02', 'music-mascots-archive', '2024-03-28', 8, 'traduzione delle tavole d''archivio nelle righe indice'),
  ('log_music-mascots-archive_03', 'music-mascots-archive', '2024-04-16', 8, 'pagine mascotte con tavole scansione e registro crediti'),
  ('log_music-mascots-archive_04', 'music-mascots-archive', '2024-05-07', 7, 'integrazione CMS per schede, etichette e coda invii'),
  ('log_music-mascots-archive_05', 'music-mascots-archive', '2024-05-28', 8, 'filtri e ricerca sull''indice archivio'),
  ('log_music-mascots-archive_06', 'music-mascots-archive', '2024-06-18', 7, 'revisioni con lo studio di graphic design sul ritmo righe e numerazione'),
  ('log_music-mascots-archive_07', 'music-mascots-archive', '2024-07-09', 6, 'anteprime WebGL al passaggio mouse sulle righe indice'),
  ('log_music-mascots-archive_08', 'music-mascots-archive', '2024-08-06', 7, 'passata responsive e budget sulle scansioni'),
  ('log_music-mascots-archive_09', 'music-mascots-archive', '2024-08-30', 5, 'messa online e QA sul dominio di produzione'),
  ('log_gastronomia-lanzani_01', 'gastronomia-lanzani', '2024-02-06', 5, 'prima chiamata e piano contenuti — prodotti, storia e negozio'),
  ('log_gastronomia-lanzani_02', 'gastronomia-lanzani', '2024-02-27', 7, 'traduzione della palette delle etichette nei template di pagina'),
  ('log_gastronomia-lanzani_03', 'gastronomia-lanzani', '2024-03-19', 8, 'pagine prodotto con registro ingredienti e abbinamenti'),
  ('log_gastronomia-lanzani_04', 'gastronomia-lanzani', '2024-04-09', 7, 'integrazione CMS per prodotti e aggiornamenti di stagione'),
  ('log_gastronomia-lanzani_05', 'gastronomia-lanzani', '2024-05-07', 6, 'revisioni con lo studio di graphic design sul trattamento fotografico'),
  ('log_gastronomia-lanzani_06', 'gastronomia-lanzani', '2024-05-28', 6, 'passata responsive e form contatti'),
  ('log_gastronomia-lanzani_07', 'gastronomia-lanzani', '2024-06-20', 5, 'messa online e primo SEO locale'),
  ('log_lorem_01', 'lorem', '2024-02-13', 5, 'prima chiamata e tassonomia — famiglie di componenti e schema nomi'),
  ('log_lorem_02', 'lorem', '2024-03-05', 7, 'traduzione dello spec tipografico nelle pagine componente'),
  ('log_lorem_03', 'lorem', '2024-03-26', 8, 'pagine componente con esempi dal vivo e registro codice'),
  ('log_lorem_04', 'lorem', '2024-04-16', 6, 'integrazione CMS per componenti e raccolte'),
  ('log_lorem_05', 'lorem', '2024-05-14', 6, 'ricerca e filtri sull''indice componenti'),
  ('log_lorem_06', 'lorem', '2024-06-01', 5, 'passata performance e messa online'),
  ('log_laura-baresi_01', 'laura-baresi', '2023-12-05', 6, 'prima chiamata e schema catalogo — varianti, giacenze e spedizioni'),
  ('log_laura-baresi_02', 'laura-baresi', '2023-12-21', 8, 'traduzione della griglia dello studio nei template shop'),
  ('log_laura-baresi_03', 'laura-baresi', '2024-01-16', 8, 'pagina prodotto con selettore varianti e guida taglie'),
  ('log_laura-baresi_04', 'laura-baresi', '2024-02-06', 8, 'carrello e ordini collegati al backend dello shop'),
  ('log_laura-baresi_05', 'laura-baresi', '2024-02-27', 7, 'integrazione CMS per collezioni e lookbook'),
  ('log_laura-baresi_06', 'laura-baresi', '2024-03-14', 6, 'revisioni con lo studio di graphic design sulla sequenza del lookbook'),
  ('log_laura-baresi_07', 'laura-baresi', '2024-04-02', 8, 'import catalogo e passata fotografica sui prodotti'),
  ('log_laura-baresi_08', 'laura-baresi', '2024-04-23', 7, 'passata responsive e budget performance sulle collezioni'),
  ('log_laura-baresi_09', 'laura-baresi', '2024-05-01', 6, 'messa online e QA del flusso ordini'),
  ('log_origami-project_01', 'origami-project', '2023-08-29', 5, 'prima chiamata e piano contenuti — laboratori, progetti e archivio'),
  ('log_origami-project_02', 'origami-project', '2023-09-19', 7, 'traduzione dell''identità a carta piegata nei template di pagina'),
  ('log_origami-project_03', 'origami-project', '2023-10-10', 8, 'pagine laboratorio con calendario e iscrizioni'),
  ('log_origami-project_04', 'origami-project', '2023-10-31', 6, 'integrazione CMS per laboratori, partner e news'),
  ('log_origami-project_05', 'origami-project', '2023-11-21', 6, 'revisioni con lo studio di graphic design sulle texture di piega'),
  ('log_origami-project_06', 'origami-project', '2023-12-12', 5, 'passata responsive e indice archivio'),
  ('log_origami-project_07', 'origami-project', '2024-01-20', 5, 'messa online e QA sul dominio di produzione'),
  ('log_omb-saleri_01', 'omb-saleri', '2023-05-09', 6, 'prima chiamata e architettura informazioni — prodotti, settori e storia azienda'),
  ('log_omb-saleri_02', 'omb-saleri', '2023-05-30', 8, 'traduzione del brochure aziendale nei template di pagina'),
  ('log_omb-saleri_03', 'omb-saleri', '2023-06-20', 8, 'catalogo prodotto con schede tecniche e libreria PDF'),
  ('log_omb-saleri_04', 'omb-saleri', '2023-07-11', 8, 'pagine settore e mappa referenze'),
  ('log_omb-saleri_05', 'omb-saleri', '2023-08-01', 6, 'setup multilingua — tre lingue e flusso traduzioni'),
  ('log_omb-saleri_06', 'omb-saleri', '2023-09-05', 7, 'integrazione CMS per prodotti, news e schede'),
  ('log_omb-saleri_07', 'omb-saleri', '2023-10-03', 6, 'revisioni con lo studio di graphic design sulle tabelle catalogo e le icone'),
  ('log_omb-saleri_08', 'omb-saleri', '2023-11-07', 8, 'passata responsive e pulizia performance sulle schede PDF'),
  ('log_omb-saleri_09', 'omb-saleri', '2023-11-20', 6, 'messa online, redirect dal vecchio sito e QA'),
  ('log_flavio-nani_01', 'flavio-nani', '2023-01-10', 5, 'prima chiamata e struttura — biografia, ruoli e contatti'),
  ('log_flavio-nani_02', 'flavio-nani', '2023-02-07', 7, 'traduzione del layout dello studio nei template di pagina'),
  ('log_flavio-nani_03', 'flavio-nani', '2023-03-02', 6, 'lista ruoli come registro consultabile con filtri'),
  ('log_flavio-nani_04', 'flavio-nani', '2023-04-04', 7, 'integrazione CMS per ruoli e news'),
  ('log_flavio-nani_05', 'flavio-nani', '2023-05-01', 5, 'revisioni con lo studio di graphic design sui ritratti, poi messa online'),
  ('log_the-big-archive_01', 'the-big-archive', '2022-08-16', 6, 'prima chiamata e tassonomia — epoche, stili e schema scheda sito'),
  ('log_the-big-archive_02', 'the-big-archive', '2022-09-06', 8, 'traduzione del layout a registro nelle righe archivio'),
  ('log_the-big-archive_03', 'the-big-archive', '2022-09-27', 8, 'pipeline di cattura — screenshot a pagina intera normalizzati in tavole'),
  ('log_the-big-archive_04', 'the-big-archive', '2022-10-18', 7, 'pagine scheda con registro metadati e indice tag'),
  ('log_the-big-archive_05', 'the-big-archive', '2022-11-08', 8, 'integrazione CMS per schede, raccolte e invii'),
  ('log_the-big-archive_06', 'the-big-archive', '2022-11-29', 8, 'ricerca e filtri per decennio sull''archivio'),
  ('log_the-big-archive_07', 'the-big-archive', '2022-12-20', 7, 'revisioni con lo studio di graphic design sul ritmo righe e numerazione'),
  ('log_the-big-archive_08', 'the-big-archive', '2023-01-24', 8, 'studio transizioni WebGL sulle tavole scheda'),
  ('log_the-big-archive_09', 'the-big-archive', '2023-02-21', 7, 'passata responsive e colonna di lettura a 44rem'),
  ('log_the-big-archive_10', 'the-big-archive', '2023-03-21', 7, 'passata performance — budget tavole e righe lazy sull''indice lungo'),
  ('log_the-big-archive_11', 'the-big-archive', '2023-05-01', 6, 'messa online e QA sul dominio di produzione'),
  ('log_massimo-uberti_01', 'massimo-uberti', '2022-11-08', 5, 'prima chiamata e struttura archivio — opere, mostre e testi'),
  ('log_massimo-uberti_02', 'massimo-uberti', '2022-11-29', 7, 'traduzione dei layout mostra nei template opera'),
  ('log_massimo-uberti_03', 'massimo-uberti', '2022-12-20', 8, 'pagine opera con fotografie grandi di luce e didascalie'),
  ('log_massimo-uberti_04', 'massimo-uberti', '2023-01-17', 7, 'integrazione CMS per opere, mostre e bibliografia'),
  ('log_massimo-uberti_05', 'massimo-uberti', '2023-02-14', 5, 'revisioni con lo studio di graphic design sul ritmo dell''indice opere'),
  ('log_massimo-uberti_06', 'massimo-uberti', '2023-03-01', 4, 'messa online e QA sul dominio di produzione'),
  ('log_francesco-bellisario_01', 'francesco-bellisario', '2022-10-18', 5, 'prima chiamata — struttura portfolio e piano archivio fotografico'),
  ('log_francesco-bellisario_02', 'francesco-bellisario', '2022-11-15', 6, 'traduzione del layout dello studio nei template di pagina'),
  ('log_francesco-bellisario_03', 'francesco-bellisario', '2022-12-06', 6, 'galleria con tavole a tutta pagina e didascalie'),
  ('log_francesco-bellisario_04', 'francesco-bellisario', '2023-01-10', 5, 'integrazione CMS per progetti e pagina about'),
  ('log_francesco-bellisario_05', 'francesco-bellisario', '2023-02-01', 4, 'messa online e QA sul dominio di produzione'),
  ('log_bloem_01', 'bloem', '2021-09-21', 5, 'prima chiamata e struttura editoriale, template longform e ritmo di lettura'),
  ('log_bloem_02', 'bloem', '2021-10-12', 8, 'traduzione della scala tipografica stampa in font variabili'),
  ('log_bloem_03', 'bloem', '2021-11-02', 7, 'template articolo con note, citazioni e tavole a tutta pagina'),
  ('log_bloem_04', 'bloem', '2021-11-23', 6, 'integrazione CMS per numeri, autori e indice archivio'),
  ('log_bloem_05', 'bloem', '2021-12-14', 5, 'passata performance — subset dei font e tavole lazy, layout stabile senza reflow'),
  ('log_bloem_06', 'bloem', '2022-01-04', 4, 'revisioni con lo studio di graphic design sulle copertine, poi messa online');
